### ISSUE TITLE
Test Framework / Build Tool Support

### ISSUE THREAD

**Issue by guybedford** [developit/web-worker#4]
The patterns encouraged by this package are awesome, but they are only as good as the tools that support them.

The use of`import.meta.url` in the analysis has limited support in build tools and test frameworks. For example in this project's own tests, `import.meta.url` can't be used due to the CommonJS conversion used in Ava. I thought it could be useful to create an issue to track support for popular test frameworks? Let me know if that sounds like a sensible approach.

### Tools to Update

- [ ] Ava test framework:
    - [ ] Blocker: `import.meta.url` is not supported in CJS
- [ ] Mocha:
    - [ ] Check if this works now that Mocha [supports native modules](https://github.com/mochajs/mocha/pull/4038)
- [ ] Jest:
    - [ ] Depends on Modules support: facebook/jest#9430
    - [ ] Update [jsdom-worker](https://github.com/developit/jsdom-worker/issues/8)
- [ ] RollupJS: Need to determine plugin combination for build support
    - [ ] Ensure this works with [rollup-plugin-off-main-thread](https://github.com/surma/rollup-plugin-off-main-thread/)
- [x] Webpack: webpack/webpack#6719
    - [ ] Fix in [worker-plugin](https://github.com/GoogleChromeLabs/worker-plugin/issues/67)
    - [ ] Fix in worker-loader
- [ ] Parcel:
    - [ ] Check to see if Parcel's default handling of Worker functions correctly with this

Feedback welcome if alternative approaches are preferable too - I don't want to make more work than necessary, but it does also seem a useful thing to do so far as it isn't too much effort to track these (and in theory the modules support naturally in these projects should align with these directions).

**Comment by erhant** [comment]
I was trying to test a repo I had using Ava, one of the packages used web-worker deep within and Ava had an error with that. I migrated everything to Mocha, and it seems to work. Perhaps you may check the box for Mocha.

I'm using `mocha@^10.2.0`.
